---

- name: Generate dynamic inventory file
  template:
    src: '{{ template_inventory }}'
    dest: '{{ inventory_dest }}/{{ template_inventory.split(".j2")[0] }}'
    mode: 0644

- name: Sleep for 60 seconds and continue with play
  wait_for:
    timeout: 60

- name: Refresh inventory
  meta: refresh_inventory
