---

- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: tmp_dir

- name: Get Terraform scripts
  git:
    repo: '{{ terraform_project_repo }}'
    dest: '{{ tmp_dir.path }}'
    version: '{{ terraform_project_version }}'

- name: Generate Terraform vars
  template:
    src: '{{ template_tfvars }}'
    dest: '{{ tmp_dir.path }}/terraform.tfvars.json'
    mode: 0644
  when: state == 'present'

- name: Create {{ ssh_files_path }}
  file:
    state: directory
    path: '{{ ssh_files_path }}'
    mode: 0700

- name: Generate SSH key
  openssh_keypair:
    path: "{{ ssh_files_path }}/{{ ssh_privkey_name }}"
    type: rsa
    size: 4096
    state: present
    force: yes
  when: state == 'present'

- name: Terraform
  terraform:
    force_init: yes
    project_path: '{{ tmp_dir.path }}'
    state: '{{ state }}'
  environment: '{{ terraform_env_vars | combine(terraform_extra_env_vars) }}'