---

- name: Get Terraform scripts
  git:
    repo: '{{ terraform_project_repo }}'
    dest: '{{ terraform_dir }}'
    version: '{{ terraform_project_version }}'

- name: Generate Ansible SA name
  set_fact:
    ansible_sa_name: 'ansible-sa-{{ 1000 | random }}'

- name: Generate Terraform vars
  template:
    src: '{{ template_tfvars }}'
    dest: '{{ terraform_dir }}/terraform.tfvars.json'
    mode: 0644
  when: state == 'present'

- name: Create {{ ssh_files_path }}
  file:
    state: directory
    path: '{{ ssh_files_path }}'
    mode: 0700

- name: Generate SSH key
  openssh_keypair:
    path: '{{ ssh_files_path }}/{{ ssh_privkey_name }}'
    type: rsa
    size: 4096
    state: present
    force: yes

- name: Terraform
  terraform:
    force_init: yes
    project_path: '{{ terraform_dir }}'
    state: '{{ state }}'
    binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' }}"
    workspace: "{{ lookup('env','MOLECULE_SCENARIO_NAME') }}"
  environment: '{{ terraform_env_vars | combine(terraform_extra_env_vars) }}'